name: amgnas
channels:
  - defaults
  - dglteam
dependencies:
  - python=3.8
  - cudatoolkit=11.0
  - dgl-cuda11.1
  - pygraphviz
  - pip:
    - ipdb
    - tqdm
    - torch==1.10.0
    - scikit-learn
    - tensorboardX
    - rich
    - pyyaml
